export const mockClothes = {
  tshirts: [
    {
      id: 1,
      title: "Джинсовая куртка",
      description: "Классическая джинсовая куртка",
      price: 5000,
      image: "/clothIMG/first.jpg",
      sizes: ["S", "M", "L", "XL"],
      colors: ["white", "black", "blue"],
    },
    {
      id: 2,
      title: "Черный бомбер",
      description: "Базовый черный бомбер",
      price: 5500,
      image: "/clothIMG/second.jpg",
      sizes: ["M", "L", "XL"],
      colors: ["black", "gray"],
    },
    {
      id: 3,
      title: "Стильный рюкзак",
      description: "Классический рюкэак из кожи",
      price: 5000,
      image: "/clothIMG/third.jpg",
      sizes: ["S", "M", "L", "XL"],
      colors: ["white", "black", "blue"],
    },
    {
      id: 4,
      title: "Красный лонгслив",
      description: "Базовый красный лонгслив oversize",
      price: 5500,
      image: "/clothIMG/four.jpg",
      sizes: ["M", "L", "XL"],
      colors: ["black", "gray"],
    },
    {
      id: 5,
      title: "Джинсовая куртка",
      description: "Классическая джинсовая куртка",
      price: 5000,
      image: "/clothIMG/first.jpg",
      sizes: ["S", "M", "L", "XL"],
      colors: ["white", "black", "blue"],
    },
    {
      id: 6,
      title: "Черный бомбер",
      description: "Базовый черный бомбер",
      price: 5500,
      image: "/clothIMG/second.jpg",
      sizes: ["M", "L", "XL"],
      colors: ["black", "gray"],
    },
    {
      id: 7,
      title: "Стильный рюкзак",
      description: "Классический рюкэак из кожи",
      price: 5000,
      image: "/clothIMG/third.jpg",
      sizes: ["S", "M", "L", "XL"],
      colors: ["white", "black", "blue"],
    },
    {
      id: 8,
      title: "Красный лонгслив",
      description: "Базовый красный лонгслив oversize",
      price: 5500,
      image: "/clothIMG/four.jpg",
      sizes: ["M", "L", "XL"],
      colors: ["black", "gray"],
    },
  ],
  jeans: [
    {
      id: 1,
      title: "Синие джинсы",
      description: "Классические прямые джинсы",
      price: 12000,
      image: "/img/jeans1.jpg",
      sizes: ["S", "M", "L", "XL"],
      colors: ["blue", "darkblue"],
    },
    {
      id: 2,
      title: "Черные джинсы",
      description: "Узкие черные джинсы",
      price: 13000,
      image: "/img/jeans2.jpg",
      sizes: ["M", "L", "XL"],
      colors: ["black"],
    },
  ],
  hoodies: [
    {
      id: 1,
      title: "Худи oversize",
      description: "Теплое худи свободного кроя",
      price: 15000,
      image: "/img/hoodie1.jpg",
      sizes: ["M", "L"],
      colors: ["black", "gray", "white"],
    },
  ],
};
