import type { Metadata } from "next";
import "./globals.css";
import { EB_Garamond } from "next/font/google";
import { ReduxProvider } from "@/components/providers";

const garamond = EB_Garamond({
  subsets: ["latin"],
  variable: "--font-garamond",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Morvien",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${garamond.variable} font-garamond antialiased bg-[#f6f6f6]`}
      >
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
