import type { Metadata } from "next";
import "./globals.css";

import { EB_Garamond, Ubuntu } from "next/font/google";

const garamond = EB_Garamond({
  subsets: ["latin"],
  variable: "--font-garamond",
  display: "swap",
});

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-ubuntu",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Morvien",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${garamond.variable} font-garamond antialiased bg-[#f6f6f6]`}
      >
        {children}
      </body>
    </html>
  );
}
